name: Deploy to Val Town

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    
    - name: Install Val Town CLI
      run: deno install -A --global -f https://esm.sh/gh/val-town/vt@0.3.0/cli.ts
    
    - name: Deploy to Val Town
      run: vt push
      env:
        VAL_TOWN_API_KEY: ${{ secrets.VAL_TOWN_API_KEY }}
